name: Wikimedia Daily Watch

on:
  schedule:
    - cron: "0 17 * * *"  # daily
  workflow_dispatch: { }

permissions:
  contents: write  # allow committing last_run.txt updates

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python monitor.py

      - name: Commit & push last_run.txt if changed
        run: |
          if [[ -n "$(git status --porcelain last_run.txt)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add last_run.txt
            git commit -m "chore: update last_run.txt [skip ci]"
            git push
          else
            echo "No changes to last_run.txt"
          fi
